### ISSUE TITLE
when server is down the exception is not correct

### ISSUE THREAD

**Issue by yegor256** [yegor256/ymock#4]
_migrated from Trac, where originally posted by **yegor256** on 16-May-2011 12:23am_

When I'm using a client without a server the following exception is thrown:

```

Caused by: java.lang.IllegalStateException: Manager is shut down.
    at org.apache.http.impl.conn.SingleClientConnManager.assertStillUp(SingleClientConnManager.java:175)
    at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:209)
    at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:190)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:391)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
    at com.ymock.client.HttpConnector.call(HttpConnector.java:82)
    at com.ymock.client.YMockClient.call(YMockClient.java:70)
    at com.raybeam.axismock.DispatcherYMock.send(DispatcherYMock.java:30)
    at com.raybeam.axismock.MockOutput.flush(MockOutput.java:50)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:124)
    at org.apache.axis.transport.http.HTTPSender.writeToSocket(HTTPSender.java:516)
    at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:138)
    ... 21 more
```

It's not correct. `YMockException` should be thrown instead.

**Comment by yegor256** [comment]
_migrated from Trac, where originally posted by **yegor256** on 16-May-2011 12:24am_

In [68/ymock]:

```
#CommitTicketReference repository="ymock" revision="68"
refs #4 - branch started
```

**Comment by yegor256** [comment]
_migrated from Trac, where originally posted by **guard** on 16-May-2011 12:52am_

In [73/ymock]:

```
#CommitTicketReference repository="ymock" revision="73"
refs #4 - /branches/ticket4 merged into /trunk, 1/2 hours spent
```

**Comment by yegor256** [comment]
_migrated from Trac, where originally posted by **guard** on 16-May-2011 12:52am_

In [74/ymock]:

```
#CommitTicketReference repository="ymock" revision="74"
refs #4 - /branches/ticket4 successfully closed
```

**Comment by yegor256** [comment]
_migrated from Trac, where originally posted by **yegor256** on 20-Nov-2011 2:56pm_

Milestone MAY11 deleted
